export const FETCH_REPOSITORY_REQUEST = 'FETCH_REPOSITORY_REQUEST'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'

export const RESPOND_REPOSITORY_REQUEST = 'RESPOND_REPOSITORY_REQUEST'
export const RESPOND_REPOSITORY_SUCCESS = 'RESPOND_REPOSITORY_SUCCESS'
export const RESPOND_REPOSITORY_FAIL = 'RESPOND_REPOSITORY_FAIL'

export const EDIT_REPOSITORY_REQUEST = 'EDIT_REPOSITORY_REQUEST'
export const EDIT_REPOSITORY_SUCCESS = 'EDIT_REPOSITORY_SUCCESS'
export const EDIT_REPOSITORY_FAIL = 'EDIT_REPOSITORY_FAIL'

export const DELETE_REPOSITORY_REQUEST = 'DELETE_REPOSITORY_REQUEST'
export const DELETE_REPOSITORY_SUCCESS = 'DELETE_REPOSITORY_SUCCESS'
export const DELETE_REPOSITORY_FAIL = 'DELETE_REPOSITORY_FAIL'
