export const FETCH_REPOSITORY_REQUEST = 'FETCH_REPOSITORY_REQUEST'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'

export const RESPOND_REPOSITORY_REQUEST = 'RESPOND_REPOSITORY_REQUEST'
export const RESPOND_REPOSITORY_SUCCESS = 'RESPOND_REPOSITORY_SUCCESS'
export const RESPOND_REPOSITORY_FAIL = 'RESPOND_REPOSITORY_FAIL'
