export const RESEARCHER_LIST_REQUEST = 'RESEARCHER_LIST_REQUEST'
export const RESEARCHER_LIST_SUCCESS = 'RESEARCHER_LIST_SUCCESS'
export const RESEARCHER_LIST_FAIL = 'RESEARCHER_LIST_FAIL'

export const RESEARCHER_APPROVE_REQUEST = 'RESEARCHER_APPROVE_REQUEST'
export const RESEARCHER_APPROVE_SUCCESS = 'RESEARCHER_APPROVE_SUCCESS'
export const RESEARCHER_APPROVE_FAIL = 'RESEARCHER_APPROVE_FAIL'
